export const KarmaReputationPresaleV2Abi = [
  // Admin Functions - createPresale
  {
    type: "function",
    name: "createPresale",
    stateMutability: "nonpayable",
    inputs: [
      { name: "presaleOwner", type: "address" },
      { name: "targetUsdc", type: "uint256" },
      { name: "minUsdc", type: "uint256" },
      { name: "duration", type: "uint256" },
      { name: "tokenSupply", type: "uint256" },
      {
        name: "deploymentConfig",
        type: "tuple",
        components: [
          {
            name: "tokenConfig",
            type: "tuple",
            components: [
              { name: "tokenAdmin", type: "address" },
              { name: "name", type: "string" },
              { name: "symbol", type: "string" },
              { name: "salt", type: "bytes32" },
              { name: "image", type: "string" },
              { name: "metadata", type: "string" },
              { name: "context", type: "string" },
              { name: "originatingChainId", type: "uint256" },
            ],
          },
          {
            name: "poolConfig",
            type: "tuple",
            components: [
              { name: "hook", type: "address" },
              { name: "pairedToken", type: "address" },
              { name: "tickIfToken0IsKarma", type: "int24" },
              { name: "tickSpacing", type: "int24" },
              { name: "poolData", type: "bytes" },
            ],
          },
          {
            name: "lockerConfig",
            type: "tuple",
            components: [
              { name: "locker", type: "address" },
              { name: "rewardAdmins", type: "address[]" },
              { name: "rewardRecipients", type: "address[]" },
              { name: "rewardBps", type: "uint16[]" },
              { name: "tickLower", type: "int24[]" },
              { name: "tickUpper", type: "int24[]" },
              { name: "positionBps", type: "uint16[]" },
              { name: "lockerData", type: "bytes" },
            ],
          },
          {
            name: "mevModuleConfig",
            type: "tuple",
            components: [
              { name: "mevModule", type: "address" },
              { name: "mevModuleData", type: "bytes" },
            ],
          },
          {
            name: "extensionConfigs",
            type: "tuple[]",
            components: [
              { name: "extension", type: "address" },
              { name: "msgValue", type: "uint256" },
              { name: "extensionBps", type: "uint16" },
              { name: "extensionData", type: "bytes" },
            ],
          },
        ],
      },
    ],
    outputs: [{ name: "presaleId", type: "uint256" }],
  },

  // Events
  {
    type: "event",
    name: "PresaleCreated",
    inputs: [
      { name: "presaleId", type: "uint256", indexed: true },
      { name: "presaleOwner", type: "address", indexed: false },
      { name: "targetUsdc", type: "uint256", indexed: false },
      { name: "minUsdc", type: "uint256", indexed: false },
      { name: "endTime", type: "uint256", indexed: false },
      { name: "scoreUploadDeadline", type: "uint256", indexed: false },
      { name: "karmaFeeBps", type: "uint256", indexed: false },
      { name: "reputationContext", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Contribution",
    inputs: [
      { name: "presaleId", type: "uint256", indexed: true },
      { name: "contributor", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "totalRaised", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ContributionWithdrawn",
    inputs: [
      { name: "presaleId", type: "uint256", indexed: true },
      { name: "contributor", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "totalRaised", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "AllocationUploaded",
    inputs: [
      { name: "presaleId", type: "uint256", indexed: true },
      { name: "user", type: "address", indexed: true },
      { name: "tokenAmount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PresaleReadyForDeployment",
    inputs: [{ name: "presaleId", type: "uint256", indexed: true }],
  },
  {
    type: "event",
    name: "PresaleDeployed",
    inputs: [
      { name: "presaleId", type: "uint256", indexed: true },
      { name: "token", type: "address", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PresaleFailed",
    inputs: [{ name: "presaleId", type: "uint256", indexed: true }],
  },
  {
    type: "event",
    name: "TokensClaimed",
    inputs: [
      { name: "presaleId", type: "uint256", indexed: true },
      { name: "user", type: "address", indexed: true },
      { name: "tokenAmount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RefundClaimed",
    inputs: [
      { name: "presaleId", type: "uint256", indexed: true },
      { name: "user", type: "address", indexed: true },
      { name: "refundAmount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "UsdcClaimed",
    inputs: [
      { name: "presaleId", type: "uint256", indexed: true },
      { name: "recipient", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "fee", type: "uint256", indexed: false },
    ],
  },

  // Errors
  { type: "error", name: "InvalidPresale", inputs: [] },
  { type: "error", name: "InvalidPresaleOwner", inputs: [] },
  { type: "error", name: "InvalidUsdcGoal", inputs: [] },
  { type: "error", name: "InvalidPresaleDuration", inputs: [] },
  { type: "error", name: "InvalidKarmaFee", inputs: [] },
  { type: "error", name: "PresaleNotLastExtension", inputs: [] },
  { type: "error", name: "PresaleSupplyZero", inputs: [] },
  { type: "error", name: "PresaleNotActive", inputs: [] },
  { type: "error", name: "PresaleNotScoresUploaded", inputs: [] },
  { type: "error", name: "PresaleNotClaimable", inputs: [] },
  { type: "error", name: "PresaleSuccessful", inputs: [] },
  { type: "error", name: "PresaleAlreadyClaimed", inputs: [] },
  { type: "error", name: "ContributionWindowEnded", inputs: [] },
  { type: "error", name: "InsufficientBalance", inputs: [] },
  { type: "error", name: "NoTokensToClaim", inputs: [] },
  { type: "error", name: "NoRefundAvailable", inputs: [] },
  { type: "error", name: "NotExpectingTokenDeployment", inputs: [] },
  { type: "error", name: "RecipientMustBePresaleOwner", inputs: [] },
  { type: "error", name: "SaltBufferNotExpired", inputs: [] },
  { type: "error", name: "DeploymentBufferExpired", inputs: [] },
  { type: "error", name: "AllocationMismatch", inputs: [] },
  { type: "error", name: "AllocationsNotComplete", inputs: [] },
  { type: "error", name: "TokenSupplyMismatch", inputs: [] },
  { type: "error", name: "Unauthorized", inputs: [] },
  { type: "error", name: "InvalidMsgValue", inputs: [] },

  // Read Functions
  {
    type: "function",
    name: "getPresale",
    stateMutability: "view",
    inputs: [{ name: "presaleId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "status", type: "uint8" },
          {
            name: "deploymentConfig",
            type: "tuple",
            components: [
              {
                name: "tokenConfig",
                type: "tuple",
                components: [
                  { name: "tokenAdmin", type: "address" },
                  { name: "name", type: "string" },
                  { name: "symbol", type: "string" },
                  { name: "salt", type: "bytes32" },
                  { name: "image", type: "string" },
                  { name: "metadata", type: "string" },
                  { name: "context", type: "string" },
                  { name: "originatingChainId", type: "uint256" },
                ],
              },
              {
                name: "poolConfig",
                type: "tuple",
                components: [
                  { name: "hook", type: "address" },
                  { name: "pairedToken", type: "address" },
                  { name: "tickIfToken0IsKarma", type: "int24" },
                  { name: "tickSpacing", type: "int24" },
                  { name: "poolData", type: "bytes" },
                ],
              },
              {
                name: "lockerConfig",
                type: "tuple",
                components: [
                  { name: "locker", type: "address" },
                  { name: "rewardAdmins", type: "address[]" },
                  { name: "rewardRecipients", type: "address[]" },
                  { name: "rewardBps", type: "uint16[]" },
                  { name: "tickLower", type: "int24[]" },
                  { name: "tickUpper", type: "int24[]" },
                  { name: "positionBps", type: "uint16[]" },
                  { name: "lockerData", type: "bytes" },
                ],
              },
              {
                name: "mevModuleConfig",
                type: "tuple",
                components: [
                  { name: "mevModule", type: "address" },
                  { name: "mevModuleData", type: "bytes" },
                ],
              },
              {
                name: "extensionConfigs",
                type: "tuple[]",
                components: [
                  { name: "extension", type: "address" },
                  { name: "msgValue", type: "uint256" },
                  { name: "extensionBps", type: "uint16" },
                  { name: "extensionData", type: "bytes" },
                ],
              },
            ],
          },
          { name: "presaleOwner", type: "address" },
          { name: "targetUsdc", type: "uint256" },
          { name: "minUsdc", type: "uint256" },
          { name: "endTime", type: "uint256" },
          { name: "scoreUploadDeadline", type: "uint256" },
          { name: "totalContributions", type: "uint256" },
          { name: "totalScore", type: "uint256" },
          { name: "deployedToken", type: "address" },
          { name: "tokenSupply", type: "uint256" },
          { name: "usdcClaimed", type: "bool" },
          { name: "karmaFeeBps", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getContribution",
    stateMutability: "view",
    inputs: [
      { name: "presaleId", type: "uint256" },
      { name: "user", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getUserScore",
    stateMutability: "pure",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getPresaleContext",
    stateMutability: "pure",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "getMaxContribution",
    stateMutability: "view",
    inputs: [
      { name: "presaleId", type: "uint256" },
      { name: "user", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getAcceptedContribution",
    stateMutability: "view",
    inputs: [
      { name: "presaleId", type: "uint256" },
      { name: "user", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getRefundAmount",
    stateMutability: "view",
    inputs: [
      { name: "presaleId", type: "uint256" },
      { name: "user", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getTokenAllocation",
    stateMutability: "view",
    inputs: [
      { name: "presaleId", type: "uint256" },
      { name: "user", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },

  {
    type: "function",
    name: "contributions",
    stateMutability: "view",
    inputs: [
      { name: "presaleId", type: "uint256" },
      { name: "user", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "tokenAllocations",
    stateMutability: "view",
    inputs: [
      { name: "presaleId", type: "uint256" },
      { name: "user", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "tokensClaimed",
    stateMutability: "view",
    inputs: [
      { name: "presaleId", type: "uint256" },
      { name: "user", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "refundClaimed",
    stateMutability: "view",
    inputs: [
      { name: "presaleId", type: "uint256" },
      { name: "user", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "expectedTokenSupply",
    stateMutability: "view",
    inputs: [{ name: "presaleId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalAllocatedTokens",
    stateMutability: "view",
    inputs: [{ name: "presaleId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalAcceptedUsdc",
    stateMutability: "view",
    inputs: [{ name: "presaleId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "factory",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "usdc",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "karmaDefaultFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "karmaFeeRecipient",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },

  // Write Functions
  {
    type: "function",
    name: "contribute",
    stateMutability: "nonpayable",
    inputs: [
      { name: "presaleId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdrawContribution",
    stateMutability: "nonpayable",
    inputs: [
      { name: "presaleId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "claim",
    stateMutability: "nonpayable",
    inputs: [{ name: "presaleId", type: "uint256" }],
    outputs: [
      { name: "tokenAmount", type: "uint256" },
      { name: "refundAmount", type: "uint256" },
    ],
  },

  // Admin Functions
  {
    type: "function",
    name: "setMaxAcceptedUsdc",
    stateMutability: "nonpayable",
    inputs: [
      { name: "presaleId", type: "uint256" },
      { name: "user", type: "address" },
      { name: "maxUsdc", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "batchSetMaxAcceptedUsdc",
    stateMutability: "nonpayable",
    inputs: [
      { name: "presaleId", type: "uint256" },
      { name: "users", type: "address[]" },
      { name: "maxUsdcAmounts", type: "uint256[]" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "maxAcceptedUsdc",
    stateMutability: "view",
    inputs: [
      { name: "presaleId", type: "uint256" },
      { name: "user", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "prepareForDeployment",
    stateMutability: "nonpayable",
    inputs: [
      { name: "presaleId", type: "uint256" },
      { name: "salt", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "receiveTokens",
    stateMutability: "payable",
    inputs: [
      {
        name: "deploymentConfig",
        type: "tuple",
        components: [
          {
            name: "tokenConfig",
            type: "tuple",
            components: [
              { name: "tokenAdmin", type: "address" },
              { name: "name", type: "string" },
              { name: "symbol", type: "string" },
              { name: "salt", type: "bytes32" },
              { name: "image", type: "string" },
              { name: "metadata", type: "string" },
              { name: "context", type: "string" },
              { name: "originatingChainId", type: "uint256" },
            ],
          },
          {
            name: "poolConfig",
            type: "tuple",
            components: [
              { name: "hook", type: "address" },
              { name: "pairedToken", type: "address" },
              { name: "tickIfToken0IsKarma", type: "int24" },
              { name: "tickSpacing", type: "int24" },
              { name: "poolData", type: "bytes" },
            ],
          },
          {
            name: "lockerConfig",
            type: "tuple",
            components: [
              { name: "locker", type: "address" },
              { name: "rewardAdmins", type: "address[]" },
              { name: "rewardRecipients", type: "address[]" },
              { name: "rewardBps", type: "uint16[]" },
              { name: "tickLower", type: "int24[]" },
              { name: "tickUpper", type: "int24[]" },
              { name: "positionBps", type: "uint16[]" },
              { name: "lockerData", type: "bytes" },
            ],
          },
          {
            name: "mevModuleConfig",
            type: "tuple",
            components: [
              { name: "mevModule", type: "address" },
              { name: "mevModuleData", type: "bytes" },
            ],
          },
          {
            name: "extensionConfigs",
            type: "tuple[]",
            components: [
              { name: "extension", type: "address" },
              { name: "msgValue", type: "uint256" },
              { name: "extensionBps", type: "uint16" },
              { name: "extensionData", type: "bytes" },
            ],
          },
        ],
      },
      {
        name: "poolKey",
        type: "tuple",
        components: [
          { name: "currency0", type: "address" },
          { name: "currency1", type: "address" },
          { name: "fee", type: "uint24" },
          { name: "tickSpacing", type: "int24" },
          { name: "hooks", type: "address" },
        ],
      },
      { name: "token", type: "address" },
      { name: "extensionSupply", type: "uint256" },
      { name: "extensionIndex", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "claimUsdc",
    stateMutability: "nonpayable",
    inputs: [
      { name: "presaleId", type: "uint256" },
      { name: "recipient", type: "address" },
    ],
    outputs: [],
  },
] as const;
